# -*- coding: utf-8 -*-
"""Llama 2 70B Chat .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jhIbCq0DbOL5Fe66H1ISgFlS95OzeCzv
"""
import pandas as pd
import os
from llama_index import (
    SimpleDirectoryReader,
    VectorStoreIndex,
    ServiceContext,
)
from llama_index.llms import LlamaCPP
from llama_index.llms.llama_utils import (
    messages_to_prompt,
    completion_to_prompt,
)

model_url = "https://huggingface.co/TheBloke/Llama-2-70B-Chat-GGUF/resolve/main/llama-2-70b-chat.Q4_K_M.gguf"

llm = LlamaCPP(
    # You can pass in the URL to a GGML model to download it automatically
    model_url=model_url,
    # optionally, you can set the path to a pre-downloaded model instead of model_url
    model_path=None,
    temperature=0.1,
    # llama2 has a context window of 4096 tokens, but we set it lower to allow for some wiggle room
    context_window=32768,
    # kwargs to pass to __call__()
    generate_kwargs={},
    model_kwargs={"n_gpu_layers": 83},
    # kwargs to pass to __init__()
    # set to at least 1 to use GPU
    # transform inputs into Llama2 format
    messages_to_prompt=messages_to_prompt,
    completion_to_prompt=completion_to_prompt,
    verbose=True,

)

df = pd.read_excel(os.path.abspath('RandomRTable.xlsx'))
df['Scoring'] = ["" for _ in range(len(df.index))]

for resume in enumerate(df['Summary']):
    print(resume)
    response = llm.complete(f"""
            You are the resume Screener. You have to see the prompt given below and according to the ask check if the Job Descirption of the job role in my company aligning with the resume given or not.

            Prompt:
            For the given Job Description and Resume, give me a score out of 100 of how eligible is the candidate to be selected. Give me advantages if any and  weakness if any of hiring the candidate based on job Description otherwise leave it blank. If the resume does not align with the given Job Description , give it 0 being the worst eligibility. Always tell if you would recommend the candidate for the given role or not.

            Job Description:
            The required skills include experience in applying machine learning and computer vision techniques/principles, experience in data preparation, designing, training, validation and deploying neural networks and other machine learning models in computer vision to solve real world problems, knowledge of accuracy, precision, recall, f1-score, RUC and deal with overfitting/underfitting problem etc., experience in building deep learning, machine learning, Reinforcement Learning, Statistical Model and fine-tuning model, developing the model on image, videos, audio data for classification, detection, recognition, and segmentation tasks using transformer and algorithm, knowledge of accuracy, precision, recall, f1-score, RUC and deal with overfitting/underfitting problem etc., experience in software development and agile methodologies preferred, experience in developing Python in the Linux environment, knowledge of database such as MySQL/PostgreSQL, excellent skills in developing Python in the Linux environment, knowledge of MySQL/PostgreSQL, proficiency in developing Python in the Linux environment, knowledge of database such as MySQL/PostgreSQL, and comfortable on Linux based OS.

            Resume:
            {resume[1]}
            
            """)
    print(response)
    df['Scoring'][resume[0]] = response
    df.to_excel(os.path.abspath('RandomRTable.xlsx'), index = False) 